language: php

php:
  - 7.2

script:
  - composer install
  - ./vendor/bin/phpcs --standard=PSR2 src tests
  - ./vendor/bin/phpstan analyse src tests --level max
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
